export enum NotificationType {
  NEW_POST = "NEW_POST",
  NEW_COMMENT = "NEW_COMMENT",
  NEW_MENTION = "NEW_MENTION",
  CONTACT_REQUEST = "CONTACT_REQUEST",
  CONTACT_ACCEPTED = "CONTACT_ACCEPTED",
  NEW_FOLLOWER = "NEW_FOLLOWER"
}
